//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderHubService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Provider : object
    {
        
        private bool CSP_IndicatorField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private ProviderHubService.Credential[] CredentialListField;
        
        private string CredentialsField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        private System.Nullable<System.DateTime> EffectiveDateField;
        
        private string EpicProviderIDField;
        
        private string ExternalProviderIDField;
        
        private string ExternalProviderNameField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private ProviderHubService.ProviderGender GenderField;
        
        private int IDField;
        
        private string InternalNotesField;
        
        private ProviderHubService.Language[] LanguageListField;
        
        private string LanguagesField;
        
        private string LastNameField;
        
        private string LastUpdatedByField;
        
        private System.DateTime LastUpdatedDateField;
        
        private bool MedicaidIndicatorField;
        
        private string MedicaidProviderIDField;
        
        private System.Nullable<System.DateTime> MedicareEffectiveDateField;
        
        private bool MedicareIndicatorField;
        
        private string MedicarePTANField;
        
        private System.Nullable<System.DateTime> MedicareTerminationDateField;
        
        private string MiddleNameField;
        
        private string NPIField;
        
        private ProviderHubService.Specialty[] ProviderSpecialtiesField;
        
        private System.Nullable<System.DateTime> TerminationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CSP_Indicator
        {
            get
            {
                return this.CSP_IndicatorField;
            }
            set
            {
                this.CSP_IndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Credential[] CredentialList
        {
            get
            {
                return this.CredentialListField;
            }
            set
            {
                this.CredentialListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credentials
        {
            get
            {
                return this.CredentialsField;
            }
            set
            {
                this.CredentialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpicProviderID
        {
            get
            {
                return this.EpicProviderIDField;
            }
            set
            {
                this.EpicProviderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalProviderID
        {
            get
            {
                return this.ExternalProviderIDField;
            }
            set
            {
                this.ExternalProviderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalProviderName
        {
            get
            {
                return this.ExternalProviderNameField;
            }
            set
            {
                this.ExternalProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.ProviderGender Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNotes
        {
            get
            {
                return this.InternalNotesField;
            }
            set
            {
                this.InternalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Language[] LanguageList
        {
            get
            {
                return this.LanguageListField;
            }
            set
            {
                this.LanguageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Languages
        {
            get
            {
                return this.LanguagesField;
            }
            set
            {
                this.LanguagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MedicaidIndicator
        {
            get
            {
                return this.MedicaidIndicatorField;
            }
            set
            {
                this.MedicaidIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicaidProviderID
        {
            get
            {
                return this.MedicaidProviderIDField;
            }
            set
            {
                this.MedicaidProviderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MedicareEffectiveDate
        {
            get
            {
                return this.MedicareEffectiveDateField;
            }
            set
            {
                this.MedicareEffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MedicareIndicator
        {
            get
            {
                return this.MedicareIndicatorField;
            }
            set
            {
                this.MedicareIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicarePTAN
        {
            get
            {
                return this.MedicarePTANField;
            }
            set
            {
                this.MedicarePTANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MedicareTerminationDate
        {
            get
            {
                return this.MedicareTerminationDateField;
            }
            set
            {
                this.MedicareTerminationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NPI
        {
            get
            {
                return this.NPIField;
            }
            set
            {
                this.NPIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Specialty[] ProviderSpecialties
        {
            get
            {
                return this.ProviderSpecialtiesField;
            }
            set
            {
                this.ProviderSpecialtiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TerminationDate
        {
            get
            {
                return this.TerminationDateField;
            }
            set
            {
                this.TerminationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credential", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Credential : object
    {
        
        private System.DateTime CreatedDateField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private int MappingIDField;
        
        private int SequenceNumberField;
        
        private bool StatusField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MappingID
        {
            get
            {
                return this.MappingIDField;
            }
            set
            {
                this.MappingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber
        {
            get
            {
                return this.SequenceNumberField;
            }
            set
            {
                this.SequenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProviderGender", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public enum ProviderGender : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Language : object
    {
        
        private System.DateTime CreatedDateField;
        
        private int IDField;
        
        private int MappingIDField;
        
        private string NameField;
        
        private int SequenceNumberField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MappingID
        {
            get
            {
                return this.MappingIDField;
            }
            set
            {
                this.MappingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber
        {
            get
            {
                return this.SequenceNumberField;
            }
            set
            {
                this.SequenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specialty", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Specialty : object
    {
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private int MappingIDField;
        
        private string NameField;
        
        private int SequenceNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MappingID
        {
            get
            {
                return this.MappingIDField;
            }
            set
            {
                this.MappingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber
        {
            get
            {
                return this.SequenceNumberField;
            }
            set
            {
                this.SequenceNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facility", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Facility : object
    {
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private string ExternalIDField;
        
        private ProviderHubService.Address FacilityAddressField;
        
        private string FacilityNameField;
        
        private int IDField;
        
        private string InternalNotesField;
        
        private string LastUpdatedByField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string NPIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID
        {
            get
            {
                return this.ExternalIDField;
            }
            set
            {
                this.ExternalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Address FacilityAddress
        {
            get
            {
                return this.FacilityAddressField;
            }
            set
            {
                this.FacilityAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacilityName
        {
            get
            {
                return this.FacilityNameField;
            }
            set
            {
                this.FacilityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNotes
        {
            get
            {
                return this.InternalNotesField;
            }
            set
            {
                this.InternalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NPI
        {
            get
            {
                return this.NPIField;
            }
            set
            {
                this.NPIField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Address : object
    {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private ProviderHubService.AddressType AddressTypeField;
        
        private string AlternatePhoneNumberField;
        
        private string CityField;
        
        private string ContactFirstNameField;
        
        private string ContactLastNameField;
        
        private string CountyField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private string EmailField;
        
        private string FaxNumberField;
        
        private int IDField;
        
        private string LastUpdatedByField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string PhoneExtensionField;
        
        private string PhoneNumberField;
        
        private string RegionField;
        
        private string StateField;
        
        private string WebsiteField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.AddressType AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternatePhoneNumber
        {
            get
            {
                return this.AlternatePhoneNumberField;
            }
            set
            {
                this.AlternatePhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactFirstName
        {
            get
            {
                return this.ContactFirstNameField;
            }
            set
            {
                this.ContactFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactLastName
        {
            get
            {
                return this.ContactLastNameField;
            }
            set
            {
                this.ContactLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber
        {
            get
            {
                return this.FaxNumberField;
            }
            set
            {
                this.FaxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneExtension
        {
            get
            {
                return this.PhoneExtensionField;
            }
            set
            {
                this.PhoneExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public enum AddressType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClinicalPracticeServiceLocation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessAdmin = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mail = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResults", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class SearchResults : object
    {
        
        private ProviderHubService.Facility[] FacilitiesField;
        
        private ProviderHubService.FacilityProviderRelationship[] FacilityProviderRelationshipsField;
        
        private ProviderHubService.Provider[] ProvidersField;
        
        private ProviderHubService.Vendor[] VendorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Facility[] Facilities
        {
            get
            {
                return this.FacilitiesField;
            }
            set
            {
                this.FacilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.FacilityProviderRelationship[] FacilityProviderRelationships
        {
            get
            {
                return this.FacilityProviderRelationshipsField;
            }
            set
            {
                this.FacilityProviderRelationshipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Provider[] Providers
        {
            get
            {
                return this.ProvidersField;
            }
            set
            {
                this.ProvidersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Vendor[] Vendors
        {
            get
            {
                return this.VendorsField;
            }
            set
            {
                this.VendorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityProviderRelationship", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class FacilityProviderRelationship : object
    {
        
        private bool AcceptingNewPatientIndicatorField;
        
        private ProviderHubService.BehavioralHealthAttribute[] BehavioralHealthAttributesField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private System.DateTime EffectiveDateField;
        
        private bool ExternalProviderIndicatorField;
        
        private ProviderHubService.Facility FacilityField;
        
        private bool FloatProviderIndicatorField;
        
        private string InternalNotesField;
        
        private string LastUpdatedByField;
        
        private System.DateTime LastUpdatedDateField;
        
        private bool PrescriberIndicatorField;
        
        private ProviderHubService.Provider ProviderField;
        
        private string ProviderEmailField;
        
        private string ProviderExtensionNumberField;
        
        private string ProviderPhoneNumberField;
        
        private bool ReferralIndicatorField;
        
        private int RelationshipIDField;
        
        private bool RelationshipStatusField;
        
        private System.DateTime TerminationDateField;
        
        private ProviderHubService.Vendor VendorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcceptingNewPatientIndicator
        {
            get
            {
                return this.AcceptingNewPatientIndicatorField;
            }
            set
            {
                this.AcceptingNewPatientIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.BehavioralHealthAttribute[] BehavioralHealthAttributes
        {
            get
            {
                return this.BehavioralHealthAttributesField;
            }
            set
            {
                this.BehavioralHealthAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExternalProviderIndicator
        {
            get
            {
                return this.ExternalProviderIndicatorField;
            }
            set
            {
                this.ExternalProviderIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Facility Facility
        {
            get
            {
                return this.FacilityField;
            }
            set
            {
                this.FacilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FloatProviderIndicator
        {
            get
            {
                return this.FloatProviderIndicatorField;
            }
            set
            {
                this.FloatProviderIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNotes
        {
            get
            {
                return this.InternalNotesField;
            }
            set
            {
                this.InternalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrescriberIndicator
        {
            get
            {
                return this.PrescriberIndicatorField;
            }
            set
            {
                this.PrescriberIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Provider Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderEmail
        {
            get
            {
                return this.ProviderEmailField;
            }
            set
            {
                this.ProviderEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderExtensionNumber
        {
            get
            {
                return this.ProviderExtensionNumberField;
            }
            set
            {
                this.ProviderExtensionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderPhoneNumber
        {
            get
            {
                return this.ProviderPhoneNumberField;
            }
            set
            {
                this.ProviderPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReferralIndicator
        {
            get
            {
                return this.ReferralIndicatorField;
            }
            set
            {
                this.ReferralIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelationshipID
        {
            get
            {
                return this.RelationshipIDField;
            }
            set
            {
                this.RelationshipIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RelationshipStatus
        {
            get
            {
                return this.RelationshipStatusField;
            }
            set
            {
                this.RelationshipStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TerminationDate
        {
            get
            {
                return this.TerminationDateField;
            }
            set
            {
                this.TerminationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Vendor Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendor", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class Vendor : object
    {
        
        private ProviderHubService.Address[] AddressesListField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedDateField;
        
        private string EPICVendorIDField;
        
        private string ExternalIDField;
        
        private int IDField;
        
        private string InternalNotesField;
        
        private string LastUpdatedByField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string NPIField;
        
        private string TaxIDField;
        
        private int VendorFacilityMappingIDField;
        
        private string VendorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.Address[] AddressesList
        {
            get
            {
                return this.AddressesListField;
            }
            set
            {
                this.AddressesListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EPICVendorID
        {
            get
            {
                return this.EPICVendorIDField;
            }
            set
            {
                this.EPICVendorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID
        {
            get
            {
                return this.ExternalIDField;
            }
            set
            {
                this.ExternalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNotes
        {
            get
            {
                return this.InternalNotesField;
            }
            set
            {
                this.InternalNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NPI
        {
            get
            {
                return this.NPIField;
            }
            set
            {
                this.NPIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxID
        {
            get
            {
                return this.TaxIDField;
            }
            set
            {
                this.TaxIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorFacilityMappingID
        {
            get
            {
                return this.VendorFacilityMappingIDField;
            }
            set
            {
                this.VendorFacilityMappingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName
        {
            get
            {
                return this.VendorNameField;
            }
            set
            {
                this.VendorNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BehavioralHealthAttribute", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public partial class BehavioralHealthAttribute : object
    {
        
        private ProviderHubService.BHAttributeType BHSpecialtyTypeField;
        
        private int MappingIDField;
        
        private int SetIDField;
        
        private bool StatusField;
        
        private string TextValueField;
        
        private int ValueIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProviderHubService.BHAttributeType BHSpecialtyType
        {
            get
            {
                return this.BHSpecialtyTypeField;
            }
            set
            {
                this.BHSpecialtyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MappingID
        {
            get
            {
                return this.MappingIDField;
            }
            set
            {
                this.MappingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SetID
        {
            get
            {
                return this.SetIDField;
            }
            set
            {
                this.SetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextValue
        {
            get
            {
                return this.TextValueField;
            }
            set
            {
                this.TextValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValueID
        {
            get
            {
                return this.ValueIDField;
            }
            set
            {
                this.ValueIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BHAttributeType", Namespace="http://schemas.datacontract.org/2004/07/ProviderHubService")]
    public enum BHAttributeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ages = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modes = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conditions = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TherapeuticApproaches = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProviderHubService.IProviderHubService")]
    public interface IProviderHubService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetData", ReplyAction="http://tempuri.org/IProviderHubService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetProviderByID", ReplyAction="http://tempuri.org/IProviderHubService/GetProviderByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Provider> GetProviderByIDAsync(int providerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetProviderLanguageByID", ReplyAction="http://tempuri.org/IProviderHubService/GetProviderLanguageByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Language[]> GetProviderLanguageByIDAsync(int providerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetProviderCredentialByID", ReplyAction="http://tempuri.org/IProviderHubService/GetProviderCredentialByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Credential[]> GetProviderCredentialByIDAsync(int providerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetFacilityByID", ReplyAction="http://tempuri.org/IProviderHubService/GetFacilityByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Facility> GetFacilityByIDAsync(int facilityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetAddressByFacilityID", ReplyAction="http://tempuri.org/IProviderHubService/GetAddressByFacilityIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Address> GetAddressByFacilityIDAsync(int facilityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetProviderList", ReplyAction="http://tempuri.org/IProviderHubService/GetProviderListResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Provider[]> GetProviderListAsync(string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetFacilityList", ReplyAction="http://tempuri.org/IProviderHubService/GetFacilityListResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Facility[]> GetFacilityListAsync(string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SearchForValue", ReplyAction="http://tempuri.org/IProviderHubService/SearchForValueResponse")]
        System.Threading.Tasks.Task<ProviderHubService.SearchResults> SearchForValueAsync(string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetFacilityProviderRelationshipList", ReplyAction="http://tempuri.org/IProviderHubService/GetFacilityProviderRelationshipListRespons" +
            "e")]
        System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship[]> GetFacilityProviderRelationshipListAsync(string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetFacilityProviderRelationshipByID", ReplyAction="http://tempuri.org/IProviderHubService/GetFacilityProviderRelationshipByIDRespons" +
            "e")]
        System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship> GetFacilityProviderRelationshipByIDAsync(int relationshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveProviderDetail", ReplyAction="http://tempuri.org/IProviderHubService/SaveProviderDetailResponse")]
        System.Threading.Tasks.Task<int> SaveProviderDetailAsync(ProviderHubService.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveFacility", ReplyAction="http://tempuri.org/IProviderHubService/SaveFacilityResponse")]
        System.Threading.Tasks.Task<int> SaveFacilityAsync(ProviderHubService.Facility facility);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveFacilityProviderRelationship", ReplyAction="http://tempuri.org/IProviderHubService/SaveFacilityProviderRelationshipResponse")]
        System.Threading.Tasks.Task<int> SaveFacilityProviderRelationshipAsync(ProviderHubService.FacilityProviderRelationship relationship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveAddress", ReplyAction="http://tempuri.org/IProviderHubService/SaveAddressResponse")]
        System.Threading.Tasks.Task<int> SaveAddressAsync(ProviderHubService.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/MapAddressToFacility", ReplyAction="http://tempuri.org/IProviderHubService/MapAddressToFacilityResponse")]
        System.Threading.Tasks.Task<int> MapAddressToFacilityAsync(int facilityID, int addressID, string createdBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetLanguageList", ReplyAction="http://tempuri.org/IProviderHubService/GetLanguageListResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Language[]> GetLanguageListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetCredentialList", ReplyAction="http://tempuri.org/IProviderHubService/GetCredentialListResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Credential[]> GetCredentialListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetVendorList", ReplyAction="http://tempuri.org/IProviderHubService/GetVendorListResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Vendor[]> GetVendorListAsync(string searchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveVendor", ReplyAction="http://tempuri.org/IProviderHubService/SaveVendorResponse")]
        System.Threading.Tasks.Task<int> SaveVendorAsync(ProviderHubService.Vendor vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/MapAddressToVendor", ReplyAction="http://tempuri.org/IProviderHubService/MapAddressToVendorResponse")]
        System.Threading.Tasks.Task<int> MapAddressToVendorAsync(int vendorID, int addressID, string createdBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetVendorByID", ReplyAction="http://tempuri.org/IProviderHubService/GetVendorByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Vendor> GetVendorByIDAsync(int vendorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetAddressByVendorID", ReplyAction="http://tempuri.org/IProviderHubService/GetAddressByVendorIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.Address[]> GetAddressByVendorIDAsync(int vendorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/MapFacilityToVendor", ReplyAction="http://tempuri.org/IProviderHubService/MapFacilityToVendorResponse")]
        System.Threading.Tasks.Task<int> MapFacilityToVendorAsync(int facilityID, int vendorID, string createdBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveLanguageByProviderID", ReplyAction="http://tempuri.org/IProviderHubService/SaveLanguageByProviderIDResponse")]
        System.Threading.Tasks.Task<bool> SaveLanguageByProviderIDAsync(int providerID, ProviderHubService.Language[] languages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveCredentialByProviderID", ReplyAction="http://tempuri.org/IProviderHubService/SaveCredentialByProviderIDResponse")]
        System.Threading.Tasks.Task<bool> SaveCredentialByProviderIDAsync(int providerID, ProviderHubService.Credential[] credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/AdvancedSearch", ReplyAction="http://tempuri.org/IProviderHubService/AdvancedSearchResponse")]
        System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship[]> AdvancedSearchAsync(System.Collections.Generic.Dictionary<string, string[]> args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetBehavioralHealthAttributeByID", ReplyAction="http://tempuri.org/IProviderHubService/GetBehavioralHealthAttributeByIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.BehavioralHealthAttribute[]> GetBehavioralHealthAttributeByIDAsync(ProviderHubService.BHAttributeType bHAttributeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/GetBHAttributeByRelationshipID", ReplyAction="http://tempuri.org/IProviderHubService/GetBHAttributeByRelationshipIDResponse")]
        System.Threading.Tasks.Task<ProviderHubService.BehavioralHealthAttribute[]> GetBHAttributeByRelationshipIDAsync(int relationshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProviderHubService/SaveBHAttributeToRelationship", ReplyAction="http://tempuri.org/IProviderHubService/SaveBHAttributeToRelationshipResponse")]
        System.Threading.Tasks.Task<bool> SaveBHAttributeToRelationshipAsync(int relationshipID, ProviderHubService.BehavioralHealthAttribute[] bhAttributeList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IProviderHubServiceChannel : ProviderHubService.IProviderHubService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ProviderHubServiceClient : System.ServiceModel.ClientBase<ProviderHubService.IProviderHubService>, ProviderHubService.IProviderHubService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProviderHubServiceClient() : 
                base(ProviderHubServiceClient.GetDefaultBinding(), ProviderHubServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProviderHubService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderHubServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProviderHubServiceClient.GetBindingForEndpoint(endpointConfiguration), ProviderHubServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderHubServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProviderHubServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderHubServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProviderHubServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderHubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Provider> GetProviderByIDAsync(int providerID)
        {
            return base.Channel.GetProviderByIDAsync(providerID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Language[]> GetProviderLanguageByIDAsync(int providerID)
        {
            return base.Channel.GetProviderLanguageByIDAsync(providerID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Credential[]> GetProviderCredentialByIDAsync(int providerID)
        {
            return base.Channel.GetProviderCredentialByIDAsync(providerID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Facility> GetFacilityByIDAsync(int facilityID)
        {
            return base.Channel.GetFacilityByIDAsync(facilityID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Address> GetAddressByFacilityIDAsync(int facilityID)
        {
            return base.Channel.GetAddressByFacilityIDAsync(facilityID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Provider[]> GetProviderListAsync(string searchValue)
        {
            return base.Channel.GetProviderListAsync(searchValue);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Facility[]> GetFacilityListAsync(string searchValue)
        {
            return base.Channel.GetFacilityListAsync(searchValue);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.SearchResults> SearchForValueAsync(string searchValue)
        {
            return base.Channel.SearchForValueAsync(searchValue);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship[]> GetFacilityProviderRelationshipListAsync(string searchValue)
        {
            return base.Channel.GetFacilityProviderRelationshipListAsync(searchValue);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship> GetFacilityProviderRelationshipByIDAsync(int relationshipID)
        {
            return base.Channel.GetFacilityProviderRelationshipByIDAsync(relationshipID);
        }
        
        public System.Threading.Tasks.Task<int> SaveProviderDetailAsync(ProviderHubService.Provider provider)
        {
            return base.Channel.SaveProviderDetailAsync(provider);
        }
        
        public System.Threading.Tasks.Task<int> SaveFacilityAsync(ProviderHubService.Facility facility)
        {
            return base.Channel.SaveFacilityAsync(facility);
        }
        
        public System.Threading.Tasks.Task<int> SaveFacilityProviderRelationshipAsync(ProviderHubService.FacilityProviderRelationship relationship)
        {
            return base.Channel.SaveFacilityProviderRelationshipAsync(relationship);
        }
        
        public System.Threading.Tasks.Task<int> SaveAddressAsync(ProviderHubService.Address address)
        {
            return base.Channel.SaveAddressAsync(address);
        }
        
        public System.Threading.Tasks.Task<int> MapAddressToFacilityAsync(int facilityID, int addressID, string createdBy)
        {
            return base.Channel.MapAddressToFacilityAsync(facilityID, addressID, createdBy);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Language[]> GetLanguageListAsync()
        {
            return base.Channel.GetLanguageListAsync();
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Credential[]> GetCredentialListAsync()
        {
            return base.Channel.GetCredentialListAsync();
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Vendor[]> GetVendorListAsync(string searchValue)
        {
            return base.Channel.GetVendorListAsync(searchValue);
        }
        
        public System.Threading.Tasks.Task<int> SaveVendorAsync(ProviderHubService.Vendor vendor)
        {
            return base.Channel.SaveVendorAsync(vendor);
        }
        
        public System.Threading.Tasks.Task<int> MapAddressToVendorAsync(int vendorID, int addressID, string createdBy)
        {
            return base.Channel.MapAddressToVendorAsync(vendorID, addressID, createdBy);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Vendor> GetVendorByIDAsync(int vendorID)
        {
            return base.Channel.GetVendorByIDAsync(vendorID);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.Address[]> GetAddressByVendorIDAsync(int vendorID)
        {
            return base.Channel.GetAddressByVendorIDAsync(vendorID);
        }
        
        public System.Threading.Tasks.Task<int> MapFacilityToVendorAsync(int facilityID, int vendorID, string createdBy)
        {
            return base.Channel.MapFacilityToVendorAsync(facilityID, vendorID, createdBy);
        }
        
        public System.Threading.Tasks.Task<bool> SaveLanguageByProviderIDAsync(int providerID, ProviderHubService.Language[] languages)
        {
            return base.Channel.SaveLanguageByProviderIDAsync(providerID, languages);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCredentialByProviderIDAsync(int providerID, ProviderHubService.Credential[] credentials)
        {
            return base.Channel.SaveCredentialByProviderIDAsync(providerID, credentials);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.FacilityProviderRelationship[]> AdvancedSearchAsync(System.Collections.Generic.Dictionary<string, string[]> args)
        {
            return base.Channel.AdvancedSearchAsync(args);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.BehavioralHealthAttribute[]> GetBehavioralHealthAttributeByIDAsync(ProviderHubService.BHAttributeType bHAttributeType)
        {
            return base.Channel.GetBehavioralHealthAttributeByIDAsync(bHAttributeType);
        }
        
        public System.Threading.Tasks.Task<ProviderHubService.BehavioralHealthAttribute[]> GetBHAttributeByRelationshipIDAsync(int relationshipID)
        {
            return base.Channel.GetBHAttributeByRelationshipIDAsync(relationshipID);
        }
        
        public System.Threading.Tasks.Task<bool> SaveBHAttributeToRelationshipAsync(int relationshipID, ProviderHubService.BehavioralHealthAttribute[] bhAttributeList)
        {
            return base.Channel.SaveBHAttributeToRelationshipAsync(relationshipID, bhAttributeList);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProviderHubService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProviderHubService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.32.0.86/ProviderHubService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProviderHubServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProviderHubService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProviderHubServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProviderHubService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProviderHubService,
        }
    }
}
